import { AntdRegistry } from '@ant-design/nextjs-registry';
import Navigations from './Component/Navigations';


export const metadata = {
  title: 'Library Management System',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body style={{margin:0}}>
      <AntdRegistry> 
        <Navigations>
          {children}
        </Navigations>
        </AntdRegistry>
        </body>
    </html>
  )
}
