import { AntdRegistry } from '@ant-design/nextjs-registry';
import Navigations from './Component/Navigations';
import { ConfigProvider } from 'antd';



export const metadata = {
  title: 'Easy Libro',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body style={{margin:0}}>
      <AntdRegistry> 
      <ConfigProvider
        theme={{
          components:{
            Button:{
             
                colorPrimary: '#001529',
                
              
            },
        }
        ,
        token:{
          colorPrimary:'#001529'
        }}}>
         
        <Navigations>
        
          {children}
          
        </Navigations>
        
        </ConfigProvider>
        </AntdRegistry>
        </body>
    </html>
  )
}
