import { AntdRegistry } from '@ant-design/nextjs-registry';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body style={{margin:0}}>
      <AntdRegistry>{children}</AntdRegistry>
        </body>
    </html>
  )
}
